In [3]:
pip install numpy

In [14]:
import numpy as np
arr_1d=np.array([1,2,3,4])
print(arr_1d)
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)
arr_3d=np.array([[7,8,9],[5,6,7],[1,2,4]])
print(arr_3d)
print(arr_2d.ndim)
print(arr_1d.ndim)
print(arr_3d.ndim)
print(arr_2d.shape)

zeros=np.zeros((2,3))
print(zeros)
ones=np.ones((3,3))
print(ones)
random_arr=np.random.random((2,2))
print(random_arr)
identity=np.eye(3)
print(identity)
range_arr=np.arange(0,10,2)
print(range_arr)



[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [5 6 7]
 [1 2 4]]
2
1
2
(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.22870123 0.0796471 ]
 [0.80736899 0.27128618]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]


In [15]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Data type:",arr.dtype)
print("Dimensions:",arr.ndim)

Shape: (2, 3)
Size: 6
Data type: int64
Dimensions: 2


In [19]:
temp_data=np.array([[22,25,20],[24,26,23]])
print(temp_data)
print("Shape:",temp_data.shape)
print("Size:",temp_data.size)
print("Data type:",temp_data.dtype)
print("Dimensions:",temp_data.ndim)
gh3=np.array([[21,23,22]])
updated_temp_data=np.append(temp_data,gh3,axis=0)
print(updated_temp_data)
sensor_error_flags=np.zeros((2,3))
print(sensor_error_flags)
greenhouse_identity=np.eye(3)
print(greenhouse_identity)


[[22 25 20]
 [24 26 23]]
Shape: (2, 3)
Size: 6
Data type: int64
Dimensions: 2
[[22 25 20]
 [24 26 23]
 [21 23 22]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr[0,1])
print(arr[1,-1])
print(arr[1,-3])
print(arr[0,2])
print(arr[])

20
60
40
30


Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.
The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array
Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.

In [26]:
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print("Apples shipped on Wednesday:")
print(shipments[0,2])
print("Oranges shipped on Sunday:")
print(shipments[1,6])
print("weekday shipments (Mon–Fri):")
print(shipments[:,0:5])
print("weekend shipments (Sat & Sun):")
print(shipments[:,5:7])
print("Apples shipments from Wednesday to Saturday:")
print(shipments[0, 2:6])
shipments[0, 5] = 100
print("Updated shipments after correction:")
print(shipments)

Apples shipped on Wednesday:
55
Oranges shipped on Sunday:
75
weekday shipments (Mon–Fri):
[[50 60 55 70 65]
 [40 45 50 60 55]]
weekend shipments (Sat & Sun):
[[80 90]
 [70 75]]
Apples shipments from Wednesday to Saturday:
[55 70 65 80]
Updated shipments after correction:
[[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  55  70  75]]


In [28]:
#Arithmetic
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a*2)
print(a*b)
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[4,5],[6,7]])
result=np.dot(mat1,mat2)
print(result)

[5 7 9]
[2 4 6]
[ 4 10 18]
[[16 19]
 [36 43]]


In [29]:
a=np.array([1,2,3])
b=2
print(a+b)

[3 4 5]


In [30]:
arr=np.array([1,2,3])
print(np.exp(arr))

[ 2.71828183  7.3890561  20.08553692]


In [36]:
import numpy as np
x=np.array([10,20,30])
y=np.array([1,2,2])
print(np.add(x,y))
print(np.subtract(x, y))
print(np.multiply(x,y))
print(np.power(x,y))
print(np.mod(x,y))


print(np.exp(x))
print(np.log(x))
print(np.log10(x))
print(np.log2(x))
print(np.expm1(x))



[11 22 32]
[ 9 18 28]
[10 40 60]
[ 10 400 900]
[0 0 0]
[2.20264658e+04 4.85165195e+08 1.06864746e+13]
[2.30258509 2.99573227 3.40119738]
[1.         1.30103    1.47712125]
[3.32192809 4.32192809 4.9068906 ]
[2.20254658e+04 4.85165194e+08 1.06864746e+13]


np.int64(6000)

In [35]:
nums = np.array([1.2, 2.5, 3.7, -1.4])
print("Round:", np.round(nums))
print("Floor:", np.floor(nums))
print("Ceil:", np.ceil(nums))
print("Trunc:", np.trunc(nums))

Round: [ 1.  2.  4. -1.]
Floor: [ 1.  2.  3. -2.]
Ceil: [ 2.  3.  4. -1.]
Trunc: [ 1.  2.  3. -1.]


In [39]:
x=np.array([10,20,30])
print(np.min(x))
print(np.max(x))
print(np.mean(x))
print(np.std(x))
print(np.var(x))
print(np.sum(x))
print(np.prod(x))

10
30
20.0
8.16496580927726
66.66666666666667
60
6000


You are a data engineer at a renewable-energy company that runs 3 solar farms.
Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.

Given data (raw)
Create arrays from these values:
production — shape (3 farms × 4 panels × 3 hours) represented as a 2D array per farm (you can stack/create as shown in tasks).
Farm A panels (rows = panels, cols = hours):


Tasks
Create arrays
Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).
Stack them into a single 3D array production_all of shape (3, 4, 3).
Array attributes
Print the .shape, .size, .dtype, and .ndim of production_all.
Per-farm totals (arithmetic & aggregation)
Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
Compute mean, std, and var per farm.
Per-hour matrix multiplication idea (matrix op)
For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)
Broadcasting adjustments
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
Apply many ufuncs (use the ufuncs listed previously)
Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:
Exponential family: np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.
Trigonometric: np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.
Rounding: np.round, np.floor, np.ceil, np.trunc.
Comparison & logical ufuncs: create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.
Bitwise ufuncs (on integer arrays): create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.
Arithmetic ufuncs again: np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.
Aggregations over ufunc outputs: e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).
Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
Final KPIs (aggregation)
Compute:
overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.

In [57]:
import numpy as np
farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])
production_all=np.array([farmA,farmB,farmC])
print("Production all:\n",production_all)
print("Size:",production_all.size)
print("Shape:",production_all.shape)
print("Dtype:",production_all.dtype)
print("Dimensions:", production_all.ndim)
total_per_farm=np.sum(production_all,axis=(1,2))
mean_per_farm=np.mean(production_all,axis=(1,2))
std_per_farm=np.std(production_all,axis=(1,2))
var_per_farm=np.var(production_all,axis=(1,2))

print("Total per farm:",total_per_farm)
print("Mean per farm:",mean_per_farm)
print("Std per farm:",std_per_farm)
print("Var per farm:",var_per_farm)
hour_weights=np.array([0.5,1.0,0.75])
weighted_per_panel=np.array([np.dot(farm, hour_weights) for farm in production_all])
print("Weighted per panel:\n", weighted_per_panel)
production_all=production_all.astype(float)
production_all[1]+=0.5
mean_farms=np.mean(production_all,axis=(1,2),keepdims=True)
std_farms=np.std(production_all,axis=(1,2),keepdims=True)
normalized=(production_all-mean_farms)/std_farms

exp_vals=np.exp(normalized)
expm1_vals=np.expm1(normalized)
log_vals=np.log(normalized - np.min(normalized) + 1)
sin_vals=np.sin(normalized)
cos_vals=np.cos(normalized)
tan_vals=np.tan(normalized)
rounded=np.round(normalized)
floored=np.floor(normalized)
ceiled=np.ceil(normalized)
truncated=np.trunc(normalized)

high_output=production_all > 20
even_hours_mask=production_all % 2==0
and_mask=np.logical_and(high_output, even_hours_mask)
or_mask=np.logical_or(high_output, even_hours_mask)
not_mask=np.logical_not(high_output)
xor_mask=np.logical_xor(high_output, even_hours_mask)

alerts=np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]])
bitwise_and=np.bitwise_and(alerts, 1)
bitwise_or=np.bitwise_or(alerts, 1)
bitwise_invert=np.bitwise_not(alerts)

panel_totals_per_farm=np.sum(production_all, axis=2)
needs_maintenance=np.any(panel_totals_per_farm < 40, axis=1)
print("Panel totals per farm:\n",panel_totals_per_farm)
print("Needs maintenance:",needs_maintenance)

overall_total=np.sum(production_all)
peak_value=np.max(production_all)
peak_index=np.argmax(production_all)
peak_farm,peak_panel,peak_hour=np.unravel_index(peak_index,production_all.shape)
avg_per_panel=np.mean(production_all, axis=2)

print("Overall total:",overall_total)
print("Peak value:",peak_value)
print(f"Peak farm:{peak_farm}, panel: {peak_panel}, hour: {peak_hour}")
print("Average per panel:\n",avg_per_panel)


Production all:
 [[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]
Size: 36
Shape: (3, 4, 3)
Dtype: int64
Dimensions: 3
Total per farm: [126 234 174]
Mean per farm: [10.5 19.5 14.5]
Std per farm: [1.97905701 1.97905701 1.97905701]
Var per farm: [3.91666667 3.91666667 3.91666667]
Weighted per panel:
 [[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]
Panel totals per farm:
 [[33.  30.  39.  24. ]
 [61.5 58.5 67.5 52.5]
 [45.  42.  51.  36. ]]
Needs maintenance: [ True False  True]
Overall total: 540.0
Peak value: 23.5
Peak farm: 1, panel: 2, hour: 1
Average per panel:
 [[11.  10.  13.   8. ]
 [20.5 19.5 22.5 17.5]
 [15.  14.  17.  12. ]]


In [63]:
arr=np.array([1,3,5,7,9,2,0,1,6])
reshaped=arr.reshape(3,3)
print(reshaped)
a=np.array([1,5,10])
b=np.array([3,8,9])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 3 5]
 [7 9 2]
 [0 1 6]]
[[ 1  5 10]
 [ 3  8  9]]
[ 1  5 10  3  8  9]


In [65]:
arr=np.array([1,2,3,4,5,6])
print(np.array_split(arr,2))

[array([1, 2, 3]), array([4, 5, 6])]


In [67]:
arr=np.array([1,4,5,3,7,8])
print(arr[arr>3])

arr=np.array([10,20,30,40])
indices=[0,2]
print(arr[indices])



[4 5 7 8]
[10 30]


In [73]:
arr=np.array([1,2,3])
view=arr.view()
view[0]=10
print(arr)
arr1=np.array([4,5,6,7])
copy=arr1.copy()
copy[1]=10
print(arr1)

[10  2  3]
[4 5 6 7]


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.

In [110]:
arr=np.arange(10,51)
print(arr)
arr1=np.random.rand(3,3)
print(arr1)
print(arr.shape)
print(arr1.shape)
print(arr.size)
print(arr1.size)
print(arr.dtype)
print(arr1.dtype)
b=5
print(arr+5)
arr2=np.random.rand(3,3)
print(arr1*arr2)

arr5=np.arange(1,26).reshape(5,5)
print(arr5[0,:])
print(arr5[:,-1])
print(arr5[:3,:2])

arr10=np.random.randint(10,101,10)
print(arr10)
print(np.max(arr10))
print(np.min(arr10))
print(np.mean(arr10))
print(np.std(arr10))

a=np.arange(1,13).reshape(3,4)
print(a)

ones_matrix=np.ones((3,3))
row_vector=np.array([1,2,3])
broadcasted=ones_matrix+row_vector

z=np.random.randint(1,51,10)
print(z[z%5==0])

mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])
mat_mult=np.dot(mat1, mat2)

o=np.arange(1,17).reshape(4,4)
print(o[np.arange(4),np.arange(4)])


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0.4157969  0.89676564 0.4431428 ]
 [0.43129625 0.90976074 0.45370001]
 [0.27268075 0.12034008 0.3424059 ]]
(41,)
(3, 3)
41
9
int64
float64
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[[0.37684064 0.79159782 0.22408695]
 [0.4205812  0.40649497 0.03544224]
 [0.12180719 0.05080949 0.26940268]]
[1 2 3 4 5]
[ 5 10 15 20 25]
[[ 1  2]
 [ 6  7]
 [11 12]]
[91 53 93 24 28 57 65 31 48 25]
93
24
51.5
24.373140954747708
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[35]
[ 1  6 11 16]
